# Generated by Django 3.1.7 on 2023-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0002_auto_20230720_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.CharField(default='No Status', max_length=2000),
        ),
    ]
