# Generated by Django 3.1.7 on 2023-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0003_auto_20230721_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.CharField(max_length=2000),
        ),
    ]
