# Generated by Django 3.1.7 on 2023-07-21 10:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0004_auto_20230721_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=100000)),
                ('post_img', models.ImageField(upload_to='user_post_images/')),
                ('time_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
