# Generated by Django 4.2.3 on 2023-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0007_auto_20230721_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='likePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
            ],
        ),
    ]
