# Generated by Django 4.2.3 on 2023-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0008_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_to_whom', models.CharField(max_length=200)),
                ('user_who_follow', models.CharField(max_length=200)),
            ],
        ),
    ]
