# Generated by Django 4.2.3 on 2023-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmedia', '0009_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user_to_whom',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_who_follow',
            field=models.CharField(max_length=2000),
        ),
    ]
